### ISSUE TITLE
Bug: LNReader v1.1.10.1 Crashing

### ISSUE THREAD

**Issue by Pheonix-Flames** [LNReader/lnreader-preview#2]
LNReader is Crashing Upon Clicking on Reader Option in settings

![Screenshot_2022-06-18-09-38-37-72_3c1c179116822eec69c21805387f0489](https://user-images.githubusercontent.com/105352597/174422276-82e1d4b7-e82a-42b2-bc71-ce9813de2705.jpg)

**Comment by rajarsheechatterjee** [comment]
Already fixed. Try changing the reader theme in reader bottom sheet for a temporary fix. Also open app related issue in the [main repo.](https://github.com/LNReader/lnreader)
